name: Get repository stats
on:
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    - cron: "0 23 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
  j1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        statsRepo:
        - fluxcd/flux2
        - fluxcd/flagger
      fail-fast: false
      max-parallel: 1
    steps:
      - name: run-ghrs
        uses: jgehrcke/github-repo-stats@v1.4.2
        with:
          repository: ${{ matrix.statsRepo }}
          ghtoken: ${{ secrets.GITHUB_TOKEN }}
